languageName: "简体中文"
languageCode: "zh-CN"
languageDirection: "ltr"
weight: 1

title: "FengKC の Blog"
copyright: "© 2026 FengKC's Blog"

params:
  displayName: "简体中文"
  isoCode: "zh"
  rtl: false
  dateFormat: "2006-01-02"
  logo: "/img/avatar.svg"
  description: "FengKC的个人博客，分享技术、记录生活"
  author: "FengKC"

  fuseOpts:
    isCaseSensitive: false
    shouldSort: true
    location: 0
    distance: 1000
    threshold: 0.4
    minMatchCharLength: 0
    keys:
      - title
      - permalink
      - summary
      - content
