languageName: "简体中文"
languageCode: "zh-CN"
languageDirection: "ltr"
weight: 1

title: "我的博客"
copyright: "© 2025 我的博客"

params:
  displayName: "简体中文"
  isoCode: "zh"
  rtl: false
  dateFormat: "2006-01-02"
  logo: "/img/avatar.svg"
  description: "一个精美的Hugo博客"
  author: "作者"

  fuseOpts:
    isCaseSensitive: false
    shouldSort: true
    location: 0
    distance: 1000
    threshold: 0.4
    minMatchCharLength: 0
    keys:
      - title
      - permalink
      - summary
      - content
