# Hugo 配置文件
baseURL = "https://feng-kc.github.io"
languageCode = "zh-CN"
title = "FengKC の Blog"
theme = "blowfish"

[taxonomies]
  tag = "tags"
  category = "categories"
  author = "authors"
  series = "series"

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true

  [markup.highlight]
    noClasses = false
    lineNos = false
    codeFences = true

  [markup.katex]
    enable = true
    html = true

[outputs]
  home = ["HTML"]
  page = ["HTML"]
  section = ["HTML"]
  taxonomy = ["HTML"]
  term = ["HTML"]
